
CREATE TABLE PRODUCTS (

          ID INTEGER NOT NULL,
          NAME VARCHAR NOT NULL,
          DESCRIPTION VARCHAR NOT NULL,
          CATEGORY VARCHAR NOT NULL,
          PRICE NUMBER(8,2) NOT NULL,
          QUANTITY INTEGER NOT NULL,

          CONSTRAINT PK_PRODUCTS PRIMARY KEY(ID)
);




CREATE TABLE CUSTOMERS (

          USERNAME VARCHAR NOT NULL,
          FIRSTNAME VARCHAR NOT NULL,
          LASTNAME VARCHAR NOT NULL,
          PASSWORD VARCHAR NOT NULL,
          EMAIL VARCHAR NOT NULL,
          CREDITCARD VARCHAR(19) NOT NULL,

          STREET VARCHAR NOT NULL,
          SUBURB VARCHAR NOT NULL,
          CITY VARCHAR NOT NULL, 
          POSTCODE INTEGER NOT NULL,

          CONSTRAINT PK_CUSTOMERS PRIMARY KEY(USERNAME)
);




CREATE TABLE ORDERS(

         orderId integer generated by default as identity (start with 1000) not null,          
         OrderDate TIMESTAMP NOT NULL,
         CustomerUsername VARCHAR NOT NULL,
         
          CONSTRAINT PK_ORDERS PRIMARY KEY(OrderId),
          CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY(CustomerUsername)references Customers(Username)
);






CREATE TABLE ORDERITEMS(

         
          Quantity INTEGER NOT NULL,
          ProductId INTEGER NOT NULL,
          OrderId INTEGER NOT NULL,
         
          constraint pk_orderitems primary key (OrderId, ProductId),
          constraint fk_orderitems_orders foreign key (OrderId) references Orders(OrderId),
          constraint fk_orderitems_products foreign key (ProductId) references Products(ID)
);